/* ═══ LE FRANÇAIS DE THE WITCHER ═════════════════════════════════════
   Trois listes, et la distinction compte — même partage que pour les cinq
   autres chaînes inversées.

   `W_IDENTIQUES` — ce qui ne se traduit pas : les titres de jeux, les
   quatorze comics sans édition française (ils portent le badge VO), le nom
   du fichier d'export. Rien n'y est écrit, donc rien n'en repart à la
   relecture.

   `W_RETROUVES` — les titres des éditions françaises et les synopsis
   français. Ils ne sont pas écrits : ils sont relevés sur
   sorceleur.fandom.com, le wiki francophone — « Quatrième de couverture »
   pour les comics et les romans, « Résumé » ou intro pour le reste. Une
   fiche sans « Titre » ni « Éditeur » y signifie qu'il n'existe pas de VF :
   c'est ce test qui décide du badge VO. Les 21 livres ont tous une édition
   française (Bragelonne / Milady) ; côté comics, Urban Comics en a publié
   sept, HiComics un seul des six albums adaptés des nouvelles, et
   CD Projekt RED a traduit « Raisons d'État ».

   `W_TRADUCTIONS` — ce qui est vraiment écrit, et qui part en relecture :
   l'accroche, les trois repères de lecture, ce qui est écarté, les cinq
   badges, et les synopsis des œuvres qui n'ont pas de page française.
   ═════════════════════════════════════════════════════════════════════ */

export const W_IDENTIQUES = [
  /* le nom du fichier d'export : une seule copie sert les deux langues */
  'chronologeek-witcher.json',
  'Sapkowski',
  'CD Projekt RED',
  'Thronebreaker: The Witcher Tales',
  'The Witcher',
  'The Witcher 2: Assassins of Kings',
  'The Witcher 3: Wild Hunt',
  'Hearts of Stone',
  'Blood and Wine',
  'Killing Monsters',
  'A Night to Remember',
  'Kiddo',
  /* les quatorze comics sans édition française : le titre reste celui de
     l'édition américaine, et la carte porte le badge VO */
  'The Witcher: The Lesser Evil',
  'The Witcher: The Edge of the World',
  'The Witcher: The Last Wish',
  'The Witcher: A Question of Price',
  'The Witcher: The Witcher',
  'The Witcher: Matters of Conscience',
  'The Witcher: Killing Monsters',
  'The Witcher: Once Upon a Time in the Woods',
  'The Witcher: Frog Kiss',
  'The Witcher: Wild Animals',
  'The Witcher: Corvo Bianco',
  'The Witcher: The Bear and the Butterfly',
  'The Witcher: Blood Stone',
  'sapkowski',
  'cdpr',
  'witcher',
  'cg-proto-witcher',
  'Chronologeek — The Witcher (proto E)',
  'Corvo Bianco',
];

export const W_RETROUVES = [
  ['The Road of No Return',
   'La Route d\'où l\'on ne revient pas'],
  ['Visenna with a bird perched on her arm finds a wounded man at a crossroads near the confluence of two rivers, Ina and Yaruga. There is a body next to him. The wounded man is called Korin. Visenna heals him using magic and hematite and he then tells her what had happened.',
   'Au cœur des monts Amell, dans la passe de Klamat, vit une monstruosité qui terrorise les villages alentours : le Kotchei. Visenna, druidesse du Cercle de Mayen et magicienne, est la seule à pouvoir vaincre cette effroyable créature. En chemin, elle porte secours à Korin, un guerrier intrépide qui finit par l\'accompagner dans sa mission.'],
  ['Crossroads of Ravens',
   'La Croisée des Corbeaux'],
  ['The book is an expansion of the story told by Geralt to Iola in The Voice of Reason 4. The action takes place in Kaedwen in 1229.',
   'On ne naît pas sorceleur. On le devient. Avant d’être connu sous le nom du Loup Blanc ou du Boucher de Blaviken, Geralt de Riv était un jeune sorceleur formé à Kaer Morhen, faisant ses premiers pas dans un monde incapable de comprendre ni d’accepter ceux de son espèce.'],
  ['A Grain of Truth',
   'Un grain de vérité'],
  ['It describes how Geralt the witcher met a man in a monster\'s mask, Nivellen.',
   'L\'histoire commence avec Geralt cherchant un raccourci à travers une vallée quand il remarque quelques oiseaux encerclant dans le ciel une zone de la forêt voisine. Il s\'y rend et y trouve le corps d\'un marchand et d\'une jeune fille. Il suit le chemin qu\'ils empruntaient : ils allaient probablement au manoir délabré au bout du chemin.'],
  ['The Lesser Evil',
   'Le Moindre Mal'],
  ['It tells the tale of how Geralt came to be known as the Butcher of Blaviken.',
   'Après avoir tué une dangereuse créature appelée Kikimorrhe, le Sorceleur se rend dans le village voisin en espérant obtenir une récompense. Il s\'adresse au magicien du village en qui il reconnaît une vieille connaissance, le magicien Stregobor qui lui causa autrefois quelques ennuis.'],
  ['The Edge of the World',
   'Le Bout du monde'],
  ['The Last Wish',
   'Le Dernier Vœu'],
  ['A Question of Price',
   'Une question de prix'],
  ['The Witcher',
   'Le Sorceleur'],
  ['It introduces the witcher Geralt and his famous fight with a striga.',
   'La fille du roi Foltest a été métamorphosée par un envoûtement en un démon appelé Strige. Chaque nuit de pleine lune elle s\'éveille et sort de son cercueil pour aller se repaître de vivants. Gerald de Riv relève le défi de lui rendre son humanité en échange d\'une rétribution conséquente.'],
  ['The Voice of Reason',
   'La Voix de la raison'],
  ['Most of this story takes place in the Temple of Melitele in Ellander while Geralt is recovering from injuries he received in a recent fight.',
   'Geralt de Riv et Iola la Première entretiennent une relation charnelle ensemble. Après s\'être fait réveiller par Nenneke au Temple de Melitele, celle-ci lui examine sa blessure reçu pendant les évènements de la nouvelle Le sorceleur.'],
  ['The Bounds of Reason',
   'Les limites du possible'],
  ['A Shard of Ice',
   'Éclat de glace'],
  ['Eternal Flame',
   'Le Feu éternel'],
  ['A Little Sacrifice',
   'Une once d\'abnégation'],
  ['It tells the tale of star-crossed trans-species lovers: a mermaid named Sh\'eenaz and a human duke named Agloval.',
   'Agloval est prince de la région maritime de Bremervoord qui est fier, orgueilleux et amoureux d\'une sirène, Sh\'eenaz. Les obstacles sont évidentes, alors le prince engage Geralt parce que les sorceleurs sont parmi ceux qui parle le Langage ancien, et s\'attend que ce dernier puisse surmonter tous les problèmes de négociation.'],
  ['The Sword of Destiny',
   'L\'Épée de la Providence'],
  ['Something More',
   'Quelque chose en plus'],
  ['Blood of Elves',
   'Le Sang des Elfes'],
  ['The empire of Nilfgaard attacks the kingdom of Cintra. Queen Calanthe commits suicide and her granddaughter, Cirilla, called Ciri and nicknamed the "Lion Cub of Cintra" manages to flee from the burning capital city. Emhyr var Emreis, Emperor of Nilfgaard, sends his spies to find her. He knows that this young girl has great importance, not only because of her royal blood, but also because of her magical potential and elven blood in her veins.',
   'Le royaume de Cintra a été entièrement détruit. Seule la petite princesse Ciri a survécu. Alors qu’elle tente de fuir la capitale, elle croise le chemin de Geralt de Riv. Pressentant chez l’enfant des dons exceptionnels, il la conduit à Kaer Morhen, l’antre des sorceleurs.'],
  ['Time of Contempt',
   'Le Temps du Mépris'],
  ['The story begins where Blood of Elves left off, essentially with Ciri and Yennefer having just left the Temple in Ellander, on their way to Gors Velen, and ultimately Thanedd Island. It is Yennefer\'s intention that Ciri be enrolled at Aretuza and that she continue her instruction in the use and mastery of magic.',
   'Le Temps du Mépris commence après le départ de Yennefer et Ciri du Temple de Melitele, alors qu\'elles sont sur la route de Gors Velen. L\'intention de Yennefer est de faire entrer Ciri à l\'école de magiciennes d\'Aretuza sur l\'île de Thanedd afin qu\'elle puisse apprendre à maîtriser la magie.'],
  ['Baptism of Fire',
   'Le Baptême du Feu'],
  ['Geralt recovers in Brokilon forest after the Thanedd incident, but he is intent on leaving as quickly as possible and continuing on his path to find Ciri. In Brokilon, he meets a young woman who will follow him on his journey towards Nilfgaard. Meanwhile, Ciri has settled into a life with some people elsewhere whom she finally can call her friends. The witcher, accompanied by Dandelion and the young woman he meets in Brokilon, undertake a dangerous journey, meeting new people along the way and discovering the truth about the mysterious Black Rider who has been plaguing Ciri\'s dreams. One of the new friends they make along the way turns out to be rather interesting...',
   'Geralt est soigné par les dryades dans la forêt de Brokilone après le Soulèvement de Thanedd, mais il a l\'intention de partir aussi rapidement que possible afin de reprendre la route sur les traces de Ciri. En effet Jaskier vient de lui apprendre que Ciri serait à Nilfgaard entre les mains de l\'empereur qui voudrait l\'épouser.'],
  ['The Tower of the Swallow',
   'La Tour de l\'Hirondelle'],
  ['One day, old Vysogota finds a very badly injured girl in the swamp surrounding his retreat. He saves her life and she tells him her story... the story of Ciri and how she became a cruel killer meeting death at every step. Until she met her retribution - Leo Bonhart, who killed her fellow bandits and captured her.',
   'Vysogota de Corvo, un vieux philosophe vivant dans les marais de Pereplut, découvre Ciri blessée près de sa retraite et prend soin d\'elle jusqu\'à ce qu\'elle soit prête à continuer son son voyage.'],
  ['The Lady of the Lake',
   'La Dame du Lac'],
  ['After walking through the portal in Tor Zireael while narrowly escaping death, Ciri finds herself in a completely different world... an Elven world. She is trapped there with no apparent way out. Time does not seem to exist and there are no obvious borders or portals to cross back into her home world.',
   'Après avoir emprunté le portail de Tor Zireael tout en échappant de justesse à la mort, Ciri se retrouve dans un monde complétement différent... Un monde elfique. Elle y est piégée avec aucun moyen apparent pour s\'évader.'],
  ['Season of Storms',
   'La Saison des Orages'],
  ['Geralt of Rivia is a Witcher, one of the few capable of hunting the monsters that prey on humanity. A mutant who is tasked with killing unnatural beings. He uses magical signs, potions, and the pride of every Witcher - two swords, steel and silver. But a contract has gone wrong, and Geralt finds himself without his signature weapons. Now he needs them back, because sorcerers are scheming, and across the world clouds are gathering. The season of storms is coming...',
   'Après un contrat dans la petite bourgade d\'Ancenis où il est amené à tuer un monstre inconnu, Idr, Geralt de Riv arrive à Kerack, une ville située entre Cidaris et Brokilone sur l\'embouchure de la rivière Adalatte. Conformément aux usages de la ville il est obligé de laisser ses épées au poste de garde pour pouvoir entrer.'],
  ['The Witcher: A Grain of Truth',
   'The Witcher : Un grain de vérité'],
  ['Geralt takes a short cut down a beaten path, where he makes a grim discovery of two corpses. Backtracking their trail, he\'s led to a derelict mansion secured with elevated walls and a gate—mysterious and ramshackle, yet adorned with a rare elegance Geralt could not ignore. He is met with the mansion\'s owner—not quite human, but a beast with the faculties of a man. With Geralt unfazed by his monstrous appearance and displays of aggression, the beast invites him inside. A kind but wary host, he shares stories of his family, his life ... and his curse. If the weight of his misdeeds could condemn him to the body of a beast—a retribution spoken of only in fairy tales, could there be another grain of truth in these tales of fantasy—one that could help him elude his fate and lead him to salvation?',
   'Un best-seller international : David Gemmell Legend Award 2009 du Meilleur roman de Fantasy. L’adaptation comics officielle de la nouvelle « Un grain de vérité ». Geralt de Riv est un homme inquiétant, un mutant devenu le parfait assassin grâce à la magie et à un long entraînement.'],
  ['The Witcher: House of Glass',
   'The Witcher : La Maison de Verre'],
  ['Traveling near the edge of the Black Forest, monster hunter Geralt meets a widowed fisherman whose dead and murderous wife resides in an eerie mansion known as the House of Glass-which seems to have endless rooms, nothing to fill them with, and horror around every corner.',
   'Poursuivant son voyage à travers la Forêt Noir, le sorceleur Geralt de Riv a rencontré les habitants de l\'étrange et sinistre Maison de Verre.'],
  ['The Witcher: Fox Children',
   'The Witcher : Les Filles-Renardes'],
  ['Geralt\'s journey leads him aboard a ship of fools, renegades, and criminals—but some passengers are more dangerous than others, and one hides a hideous secret!',
   'Le voyage du sorceleur Geralt de Riv le conduit cette fois-ci à bord d\'un étrange navire. À son bord, des fous, des renégats ou bien encore de dangereux criminels.'],
  ['The Witcher: Reasons of State',
   'The Witcher : Raisons d’État'],
  ['The story is set in the barony of Creigiau in Malleore in 1262, after the First Northern War.',
   'L\'an de grâce 1262. après avoir sauvé Ciri des griffes des dryades de Brokilon, Geralt fait route vers le nord. au même moment, la guerre éclate contre nilfgaard, une guerre qui s’est jouée lors de la bataille sur la colline de sodden et qui, semblait-il, aurait coûté la vie à Yennefer de Vengerberg.'],
  ['Thronebreaker is a single player role-playing game set in the world of The Witcher that combines narrative-driven exploration with unique puzzles and card battle mechanics.',
   'Thronebreaker: The Witcher Tales est un jeu de rôle solo se déroulant dans l\'univers de The Witcher, en combinant de l\'exploration scénarisée avec des énigmes uniques et les mécaniques d\'un jeu de cartes.'],
  ['The Witcher is the very first instalment of the series that follows the story of Geralt from Rivia. Being found unconscious on the battlefield he must retrieve his memory and help the emperor\'s daughter, Adda to stop her from turning in to a feral monster. Facing the biggest enemy, Salamander, Geralt must also help all the fractions around the world to find peace between each other.',
   'The Witcher raconte l\'histoire de Geralt, un homme qui est devenu un "Sorceleur" — un chasseur de monstres doté de pouvoirs surnaturels. L\'action se situe dans un monde médiéval que le jeu met en valeur par de nombreux détails visuels.'],
  ['The Price of Neutrality',
   'Le Prix de la Neutralité'],
  ['The famous bard Dandelion has stopped by at an inn. Naturally, the patrons wish to hear a ballad and so he sings the lay of the "Bitter, Evil Hearts". Set in the fall of 1232 in the valley surrounding Kaer Morhen, the ballad finds Geralt coming back to the witchers\' home for the winter when he unexpectedly spies a small camp just outside the stronghold. This comes as quite a surprise since the way to Kaer Morhen is a closely guarded secret. One could count on one hand the number of non-witchers who know the way.',
   'Le légendaire Loup Blanc, Geralt de Riv, revient pour l\'hiver à Kaer Morhen, la forteresse secrète des sorceleurs tapie au cœur des Montagnes Bleues. Là, il constate que des invités inattendus sont arrivés avant lui, amenant les ennuis dans leur sillage.'],
  ['Side Effects',
   'Effets secondaires'],
  ['The third game in a series, it holds nothing back from the player. Open world adventures of the renowned monster slayer Geralt of Rivia are now even on a larger scale. Following the source material more accurately, this time Geralt is trying to find the child of the prophecy, Ciri while making a quick coin from various contracts on the side. Great attention to the world building above all creates an immersive story, where your decisions will shape the world around you.',
   'The Witcher 3: Wild Hunt a été récompensé par le titre de Game Of The Year (GOTY) 2015. Le jeu s\'est élevé au niveau des tous meilleurs RPG de tous les temps et plus de deux ans après sa sortie il s\'est imposé comme un étalon en termes de graphismes, de monde ouvert, de RPG scénarisé et de durée de vie pour son ensemble de quêtes…'],
  ['Hearts of Stone is the first official expansion pack for The Witcher 3: Wild Hunt—an award-winning role-playing game set in a vast fantasy open world. Become Geralt of Rivia, a professional monster slayer hired to defeat a ruthless bandit captain, Olgierd von Everec, a man who possesses the power of immortality. Hearts of Stone packs over 10 hours of new adventures, introducing new characters, powerful monsters, unique romance and a brand new storyline shaped by your choices.',
   'Hearts of Stone emportera Geralt dans une nouvelle aventure d\'une dizaine d\'heures dans les Terres désolées et les recoins d\'Oxenfurt, où il tentera de remplir un contrat pour l\'énigmatique Homme de verre. Confronté aux mensonges, Geralt aura besoin de toute son intelligence et sa force pour résoudre le mystère et s\'en sortir indemne.'],
  ['The Witcher: Curse of Crows',
   'The Witcher : La Malédiction des corbeaux'],
  ['Witchers Geralt and Ciri become embroiled in a brutal story of revenge when an old enemy creates a monster to kill them. What seems like a simple rescue mission quickly becomes more complex and dangerous with the involvement of werewolf-like creatures known as strigas.',
   'Après avoir survécu à la Chasse Sauvage et sauvé le monde d’un hiver éternel, Geralt de Riv poursuit la formation de sa protégée, Ciri, au rude métier de Sorceleur. Sur la piste d’une strige terrorisant les environs de Novigrad, l’apprentie chasseuse de monstres cherche à en savoir toujours plus sur la créature.'],
  ['The Witcher: Of Flesh and Flame',
   'The Witcher : De chair et de flamme'],
  ['Geralt is summoned by an old friend to help solve a mystery involving his daughter. Upon his arrival, Geralt is surprised by another friend from the past and he soon finds himself transported to regions beyond his original expectations.',
   'De retour à Novigrad, Geralt accepte de protéger la fille d\'un notable des assauts d\'un soupirant trop entreprenant. La mission du sorceleur s\'achève lorsqu\'il découvre l\'identité de l\'amant : il s\'agit de Jaskier, conteur, troubadour et chroniqueur officiel de la saga du Loup Blanc.'],
  ['The Witcher: Witch\'s Lament',
   'The Witcher : La Complainte de la sorcière'],
  ['The Witcher: Witch\'s Lament follows famed witcher Geralt after a routine hunt. But when the captured witch is burned at the stake, Geralt is haunted by images of her death, and a harrowing warning begins to take shape. Soon, Geralt finds himself drawn into the mystery surrounding this heinous persecution.',
   'Les flammes s\'élèvent alors qu\'une sorcière brûle sur le bûcher. Geralt, en quête de sa prochaine mission, reste hanté par les images de cette fatale exécution, comme une menace sourde.'],
  ['The Witcher: The Ballad of Two Wolves',
   'The Witcher : La Ballade des deux loups'],
  ['Hailed as the greatest monster slayer--the infamous witcher Geralt is beckoned to the town of Grimmwald. When a strange occurrence stirs murmurs of a werewolf on the prowl, rumors spread about the peculiar arrival of three sisters. With a grand mystery and a monster to kill, Dandelion may just find the inspiration he needs to write the perfect ballad.',
   'Réputé pour être un tueur de monstres sans pitié, le sorceleur Geralt est appelé dans la ville de Grimmwald. Théâtre d\'événements étranges, des bruits courent qu\'un loup-garou y rôde, tandis que l\'arrivée de trois soeurs fortunées auraient transformé la ville pauvre en une destination touristique prisée.'],
  ['Welcome to the land of summer, a remote valley untouched by war. The land of wandering knights, noble ladies and magnificent wineries. What better time to visit than now, when this kingdom of virtue is torn apart by a series of savage massacres! Geralt of Rivia, a legendary monster slayer, takes on his last great contract. Blood and Wine offers over 30 hours of adventure, where beauty clashes with horror, and love dances with deceit.',
   'Blood and Wine est la seconde et dernière extension pour The Witcher 3: Wild Hunt. Annoncée le 7 avril 2015, avec Hearts of Stone, elle est sortie le 31 mai 2016 sur PC, Xbox One et Playstation 4. Cette extension fait intervenir de nouveaux personnages, monstres, armures, armes, ainsi qu\'un nouveau jeu de Gwynt.'],
  ['The Witcher: Fading Memories',
   'The Witcher : Souvenirs lointains'],
  ['Geralt has become impoverished and dejected since monster threats have seemingly vanished. Times have always been hard for Witchers—but without continual work, his situation has worsened. As Geralt explores new possibilities for his life path, he receives a request from the mayoress of Badreine, a small town where an unusual pack of foglets attacks children... but something feels off about this new threat.',
   'Alors que les attaques de monstres se font de plus en plus rares, il devient difficile pour Geralt de vivre de son métier de Sorceleur. Alors qu\'il explore d\'autres possibilités de carrière, il reçoit une requête de la maire d\'une petite ville dont les enfants sont régulièrement capturés par des foglets.'],
  ['The Last Wish',
   'Le Dernier Vœu'],
  ['Sword of Destiny',
   'L\'Épée de la Providence'],
  ['How to read this',
   'Repères de lecture'],
  ['FLASHBACKS',
   'LES FLASHBACKS'],
  ['What\'s left out, and why',
   'Ce qui est écarté, et pourquoi'],
  ['3 entries',
   '3 entrées'],
  ['Lady of the Lake',
   'La Dame du Lac'],
  ['It describes how Geralt the witcher met a man in a monster&#x27;s mask, Nivellen.',
   'L\'histoire commence avec Geralt cherchant un raccourci à travers une vallée quand il remarque quelques oiseaux encerclant dans le ciel une zone de la forêt voisine. Il s\'y rend et y trouve le corps d\'un marchand et d\'une jeune fille. Il suit le chemin qu\'ils empruntaient : ils allaient probablement au manoir délabré au bout du chemin.'],
  ['It tells the tale of star-crossed trans-species lovers: a mermaid named Sh&#x27;eenaz and a human duke named Agloval.',
   'Agloval est prince de la région maritime de Bremervoord qui est fier, orgueilleux et amoureux d\'une sirène, Sh\'eenaz. Les obstacles sont évidentes, alors le prince engage Geralt parce que les sorceleurs sont parmi ceux qui parle le Langage ancien, et s\'attend que ce dernier puisse surmonter tous les problèmes de négociation.'],
  ['The empire of Nilfgaard attacks the kingdom of Cintra. Queen Calanthe commits suicide and her granddaughter, Cirilla, called Ciri and nicknamed the &quot;Lion Cub of Cintra&quot; manages to flee from the burning capital city. Emhyr var Emreis, Emperor of Nilfgaard, sends his spies to find her. He knows that this young girl has great importance, not only because of her royal blood, but also because of her magical potential and elven blood in her veins.',
   'Le royaume de Cintra a été entièrement détruit. Seule la petite princesse Ciri a survécu. Alors qu’elle tente de fuir la capitale, elle croise le chemin de Geralt de Riv. Pressentant chez l’enfant des dons exceptionnels, il la conduit à Kaer Morhen, l’antre des sorceleurs.'],
  ['The story begins where Blood of Elves left off, essentially with Ciri and Yennefer having just left the Temple in Ellander, on their way to Gors Velen, and ultimately Thanedd Island. It is Yennefer&#x27;s intention that Ciri be enrolled at Aretuza and that she continue her instruction in the use and mastery of magic.',
   'Le Temps du Mépris commence après le départ de Yennefer et Ciri du Temple de Melitele, alors qu\'elles sont sur la route de Gors Velen. L\'intention de Yennefer est de faire entrer Ciri à l\'école de magiciennes d\'Aretuza sur l\'île de Thanedd afin qu\'elle puisse apprendre à maîtriser la magie.'],
  ['Geralt recovers in Brokilon forest after the Thanedd incident, but he is intent on leaving as quickly as possible and continuing on his path to find Ciri. In Brokilon, he meets a young woman who will follow him on his journey towards Nilfgaard. Meanwhile, Ciri has settled into a life with some people elsewhere whom she finally can call her friends. The witcher, accompanied by Dandelion and the young woman he meets in Brokilon, undertake a dangerous journey, meeting new people along the way and discovering the truth about the mysterious Black Rider who has been plaguing Ciri&#x27;s dreams. One of the new friends they make along the way turns out to be rather interesting...',
   'Geralt est soigné par les dryades dans la forêt de Brokilone après le Soulèvement de Thanedd, mais il a l\'intention de partir aussi rapidement que possible afin de reprendre la route sur les traces de Ciri. En effet Jaskier vient de lui apprendre que Ciri serait à Nilfgaard entre les mains de l\'empereur qui voudrait l\'épouser.'],
  ['Geralt takes a short cut down a beaten path, where he makes a grim discovery of two corpses. Backtracking their trail, he&#x27;s led to a derelict mansion secured with elevated walls and a gate—mysterious and ramshackle, yet adorned with a rare elegance Geralt could not ignore. He is met with the mansion&#x27;s owner—not quite human, but a beast with the faculties of a man. With Geralt unfazed by his monstrous appearance and displays of aggression, the beast invites him inside. A kind but wary host, he shares stories of his family, his life ... and his curse. If the weight of his misdeeds could condemn him to the body of a beast—a retribution spoken of only in fairy tales, could there be another grain of truth in these tales of fantasy—one that could help him elude his fate and lead him to salvation?',
   'Un best-seller international : David Gemmell Legend Award 2009 du Meilleur roman de Fantasy. L’adaptation comics officielle de la nouvelle « Un grain de vérité ». Geralt de Riv est un homme inquiétant, un mutant devenu le parfait assassin grâce à la magie et à un long entraînement.'],
  ['Geralt&#x27;s journey leads him aboard a ship of fools, renegades, and criminals—but some passengers are more dangerous than others, and one hides a hideous secret!',
   'Le voyage du sorceleur Geralt de Riv le conduit cette fois-ci à bord d\'un étrange navire. À son bord, des fous, des renégats ou bien encore de dangereux criminels.'],
  ['The Witcher is the very first instalment of the series that follows the story of Geralt from Rivia. Being found unconscious on the battlefield he must retrieve his memory and help the emperor&#x27;s daughter, Adda to stop her from turning in to a feral monster. Facing the biggest enemy, Salamander, Geralt must also help all the fractions around the world to find peace between each other.',
   'The Witcher raconte l\'histoire de Geralt, un homme qui est devenu un "Sorceleur" — un chasseur de monstres doté de pouvoirs surnaturels. L\'action se situe dans un monde médiéval que le jeu met en valeur par de nombreux détails visuels.'],
  ['The famous bard Dandelion has stopped by at an inn. Naturally, the patrons wish to hear a ballad and so he sings the lay of the &quot;Bitter, Evil Hearts&quot;. Set in the fall of 1232 in the valley surrounding Kaer Morhen, the ballad finds Geralt coming back to the witchers&#x27; home for the winter when he unexpectedly spies a small camp just outside the stronghold. This comes as quite a surprise since the way to Kaer Morhen is a closely guarded secret. One could count on one hand the number of non-witchers who know the way.',
   'Le légendaire Loup Blanc, Geralt de Riv, revient pour l\'hiver à Kaer Morhen, la forteresse secrète des sorceleurs tapie au cœur des Montagnes Bleues. Là, il constate que des invités inattendus sont arrivés avant lui, amenant les ennuis dans leur sillage.'],
  ['The Witcher: Witch&#x27;s Lament',
   'The Witcher : La Complainte de la sorcière'],
  ['The Witcher: Witch&#x27;s Lament follows famed witcher Geralt after a routine hunt. But when the captured witch is burned at the stake, Geralt is haunted by images of her death, and a harrowing warning begins to take shape. Soon, Geralt finds himself drawn into the mystery surrounding this heinous persecution.',
   'Les flammes s\'élèvent alors qu\'une sorcière brûle sur le bûcher. Geralt, en quête de sa prochaine mission, reste hanté par les images de cette fatale exécution, comme une menace sourde.'],
  ['What&#x27;s left out, and why',
   'Ce qui est écarté, et pourquoi'],
];

export const W_TRADUCTIONS = [
  // « Remaining » et « completed » à l'accroche depuis le 21 septembre 2026
  ['Remaining', 'Restant'],
  ['Check off what you\'ve completed — your progress is saved.', 'Cochez ce que vous avez complété, votre progression est sauvegardée.'],
  // « completed » partout depuis le 21 septembre 2026 : une timeline qui mêle
  // livres, jeux et écrans ne dit plus un verbe en oubliant les autres
  ['completed', 'terminés'],
  ['completed</span>', 'terminés</span>'],
  ['Hide completed', 'Masquer les terminés'],
  ['It recounts the first adventure Dandelion and Geralt went on together.',
   'Elle raconte la première aventure que Jaskier et Geralt ont menée ensemble.'],
  ['This story describes the circumstances of Geralt and Yennefer\'s first meeting.',
   'Cette nouvelle raconte les circonstances de la première rencontre entre Geralt et Yennefer.'],
  ['The story begins with Geralt being clean-shaven, washed and nicely clothed by the servants and castellan Haxo of the royal family\'s castle in Cintra. Cintra\'s crown-princess, Pavetta, has turned fifteen years old and, as is the custom, contenders for her hand have turned up by the dozen. Geralt asks the castellan, Haxo, why he was invited and is told that the queen very much wants to ensure that Cintra becomes allied with Skellige and that a witchers services are likely required to ensure this outcome.',
   'L\'histoire commence avec Geralt rasé de près, lavé et vêtu par les serviteurs et le castellan Haxo, au château de la famille royale de Cintra. Pavetta, princesse héritière de Cintra, vient d\'avoir quinze ans et, comme le veut la coutume, les prétendants à sa main sont arrivés par dizaines. Geralt demande au castellan pourquoi il a été convié : la reine tient à ce que Cintra s\'allie à Skellige, et les services d\'un sorceleur seront sans doute nécessaires pour que cette alliance se fasse.'],
  ['This is the story of a hunt for a legendary golden dragon Villentretenmerth. The story also expands on the relationship between the sorceress Yennefer and Geralt the witcher, which began in earlier short stories.',
   'C\'est l\'histoire d\'une chasse au légendaire dragon d\'or Villentretenmerth. La nouvelle approfondit aussi la relation entre la magicienne Yennefer et Geralt le sorceleur, commencée dans les nouvelles précédentes.'],
  ['In the story we learn more about Geralt\'s history with the sorceress Yennefer.',
   'On y apprend un peu plus sur le passé de Geralt avec la magicienne Yennefer.'],
  ['The story is set in and around Novigrad and tells the story of how Geralt met Dudu.',
   'L\'histoire se déroule à Novigrad et dans ses environs, et raconte comment Geralt a rencontré Dudu.'],
  ['It is in this story that Geralt and Ciri, his law of surprise, are first introduced to one another.',
   'C\'est dans cette nouvelle que Geralt et Ciri, son enfant-surprise, se rencontrent pour la première fois.'],
  ['It takes place after the fall of Cintra, as Geralt is on the road heading towards Cintra in hopes of finding Ciri.',
   'Elle se déroule après la chute de Cintra, alors que Geralt est sur la route de Cintra dans l\'espoir d\'y retrouver Ciri.'],
  ['In search of a reward, Geralt brings the carcass of a slain creature to a small town where he is told it may be of use to the local sorcerer - but the mage isn\'t who he is alleged to be. In hiding for his life, he requests Geralt\'s help in slaying the monster who seeks to murder him - a young woman said to have been born under the Curse of the Black Sun - a prophecy of inborn evil. He declares that she is more a monster than the creature presented before him. Geralt later encounters the woman, who asserts that it is the sorcerer who is the true monster - committing unspeakable crimes at the behest of his superstitious beliefs. With the boundaries blurred between the evil that is done and the evil done in return, Geralt is met with a quandary. The face of evil is ever-changing and his verdict, whether by choice or by force, can only lead to tragedy.',
   'En quête d\'une récompense, Geralt apporte la dépouille d\'une créature dans une petite ville, où l\'on prétend que le magicien du cru pourrait en avoir l\'usage — mais le mage n\'est pas celui qu\'il dit être. Terré pour sauver sa vie, il demande à Geralt de tuer le monstre qui veut sa mort : une jeune femme née, dit-on, sous la Malédiction du Soleil noir, une prophétie de mal inné. Il la déclare plus monstrueuse que la créature posée devant lui. Geralt croise ensuite la jeune femme, pour qui le véritable monstre est le magicien, coupable de crimes indicibles au nom de ses croyances. La frontière entre le mal commis et le mal rendu s\'effaçant, Geralt se retrouve devant un dilemme : le visage du mal ne cesse de changer, et son verdict, choisi ou imposé, ne peut mener qu\'à la tragédie.'],
  ['Work is hard to come by for Geralt and with Dandelion, not a subject for his rhymes or ballads. As they travel to the edge of the known world, townsfolk speak of many stories but it seems that\'s all they are—recitals of monsters and superstition—until a man follows Geralt with news of a devil scavenging the local fields. Rid the beast, but under no condition is he to be killed. Only how can Geralt hunt the creature, for there is no such things as devils...',
   'Le travail se fait rare pour Geralt, et avec Jaskier, ce n\'est pas un sujet de ballade. Tandis qu\'ils gagnent le bout du monde connu, les villageois content mille histoires qui ne sont que cela — récits de monstres et superstitions — jusqu\'à ce qu\'un homme rattrape Geralt : un diable ravage les champs des environs. Qu\'il en débarrasse le pays, mais sous aucun prétexte il ne doit le tuer. Reste à savoir comment chasser une créature qui n\'existe pas, puisque les diables n\'existent pas…'],
  ['The desire for power unleashes chaos and seals a new destiny in this graphic novel adaptation of Andrzej Sapkowski\'s short story. Driven by unhealthy curiosity, Dandelion breaks a magic seal and unleashes a djinn whom he hopes will grant his wishes. Instead, the creature attacks him, leaving him with wounds only a mage can heal. Geralt rushes the bard to a nearby town, but in a city where casting spells carries heavy penalties, there is only one sorceress who resides—Yennefer of Vengerberg. Despite her beauty, grace, and zeal, can she be trusted? With the djinn set loose, Geralt is at the mercy of magic. And as a struggle for power and control begins, wishes are made, but whose are being granted?',
   'La soif de pouvoir déchaîne le chaos et scelle un destin, dans cette adaptation en bande dessinée de la nouvelle d\'Andrzej Sapkowski. Poussé par une curiosité malsaine, Jaskier brise un sceau magique et libère un djinn dont il espère qu\'il exaucera ses vœux. La créature l\'attaque et le laisse blessé au point que seule la magie peut le sauver. Geralt conduit le barde jusqu\'à la ville voisine, où lancer un sort coûte cher et où ne réside qu\'une seule magicienne : Yennefer de Vengerberg. Malgré sa beauté, sa grâce et son ardeur, peut-on lui faire confiance ? Le djinn lâché dans la nature, Geralt est à la merci de la magie. Et tandis que s\'engage une lutte de pouvoir, des vœux sont formulés — mais à qui sont-ils accordés ?'],
  ['Geralt is invited to a banquet at the Kingdom of Cintra. The Princess has come of age and suitors prepare to present themselves for her hand in marriage. Wary of the Queen\'s invitation, Geralt attends the dinner with caution. When a mysterious uninvited guest, bearing the armor of a knight enters the hall, a bold declaration and a shocking revelation ignites the party into chaos and uproar.',
   'Geralt est convié à un banquet au royaume de Cintra. La princesse est en âge de se marier, et les prétendants s\'apprêtent à demander sa main. Méfiant devant l\'invitation de la reine, Geralt s\'installe à table sur ses gardes. Lorsqu\'un convive mystérieux, en armure de chevalier, entre dans la salle, une déclaration audacieuse et une révélation renversante jettent le banquet dans le chaos.'],
  ['Sin manifests into bloodlust in this graphic novel adaptation of Andrzej Sapkowski\'s original short story. Geralt pursues a proclamation from a king of a bloodthirsty monster plaguing his palace. A hefty reward is offered to cure the beast, but not to kill it, for the king holds a secret—what lies beneath the palace is beyond the spawn of evil. Tried and failed by charlatans, Geralt sets out to claim the bounty—by decree of the king or by the pleas of those who wish the creature dead.',
   'Le péché se mue en soif de sang dans cette adaptation en bande dessinée de la nouvelle d\'Andrzej Sapkowski. Geralt répond à la proclamation d\'un roi dont le palais est hanté par un monstre assoiffé de sang. La récompense est lourde, mais elle va à qui guérira la bête, pas à qui la tuera : le roi garde un secret, et ce qui dort sous le palais n\'est pas qu\'une engeance du mal. Après l\'échec des charlatans, Geralt part réclamer la prime — par décret du roi ou par les supplications de ceux qui veulent la créature morte.'],
  ['While still enjoying the inn, the patrons, after listening to Dandelion singing his first ballad, wish to hear another story. This tale, set one year after Geralt tamed the striga the first time, starts in a rather unoriginal way — in (Vizima\'s) prison. The twist is that, this time, Geralt is the person visiting someone, not the one behind bars. So who is the unfortunate fellow? It is Dandelion of course, Geralt\'s old pal, and once again he has gotten himself into trouble. Because Geralt is his friend, the task of getting the bard off the hook falls to the witcher, once again ("... I promise Geralt, that\'s the last time, or almost the last time, really!").',
   'Toujours à l\'auberge, les clients, après la première ballade de Jaskier, en réclament une autre. Ce récit-là, situé un an après que Geralt a maîtrisé la strige, commence de façon fort banale : en prison, à Vizima. À ceci près que cette fois, Geralt est celui qui rend visite, et non celui qui est derrière les barreaux. Le malheureux, c\'est Jaskier, bien sûr, encore une fois dans de mauvais draps — et c\'est au sorceleur, en ami, de l\'en sortir.'],
  ['The Witcher 2: Assassins of Kings features a thoroughly engrossing, mature storyline that defines a new standard for realistic,non-linear game narration. In addition to an epic story, the game features a complex combat system that uniquely combines deep tactical elements with dynamic action.',
   'The Witcher 2: Assassins of Kings porte une histoire adulte et prenante, qui pose une nouvelle référence en matière de narration non linéaire. À ce récit s\'ajoute un système de combat complexe, qui mêle profondeur tactique et action nerveuse.'],
  ['The year was 1271. The place - Vergen. The moment - portentous. King Henselt\'s long siege had finally ended. Life was slowly returning to normal - or as "normal" as it could be in a city where humans, dwarves and elves lived side by side and in harmony, the whole powder keg led by a maiden... And not just any maiden, mind you, but the virgin and heroine Saskia, until recently known as the Dragonslayer, before she was revealed to be a dragon herself.',
   'Nous sommes en 1271, à Vergen, et le moment est de ceux qui comptent. Le long siège du roi Henselt vient de prendre fin et la vie reprend son cours — autant qu\'elle le peut dans une ville où humains, nains et elfes vivent côte à côte, ce baril de poudre étant mené par une jeune femme. Et pas n\'importe laquelle : l\'héroïne Saskia, dite la Tueuse de dragons, jusqu\'à ce qu\'on découvre qu\'elle en était un.'],
  ['The plot is set before the events shown in the Killing Monsters cinematic trailer. In the comics, Vesemir and Geralt are looking for Yennefer. In the small town of Vorune, occupied by troops of Nilfgaard, they are looking for work and take a contract for 40 Florens to kill a man-eating monster. A Fiend called Drugan no less. But the giant beast is not the only murderer in this region...',
   'L\'histoire se place avant les événements du trailer Killing Monsters. Vesemir et Geralt sont à la recherche de Yennefer. Dans la petite ville de Vorune, occupée par les troupes de Nilfgaard, ils cherchent du travail et acceptent un contrat de 40 florins pour tuer un monstre mangeur d\'hommes : un Sylvain nommé Drugan, rien de moins. Mais la bête n\'est pas le seul assassin de la région…'],
  ['In The Witcher, it\'s an original tale featuring the iconic witcher, Geralt! Created in close collaboration with CD PROJEKT RED!',
   'Un récit inédit mettant en scène le sorceleur Geralt, créé en étroite collaboration avec CD PROJEKT RED.'],
  ['In The Witcher: Frog Kiss, Geralt must uncover why the young women in Novigrad are turning into frogs!',
   'Geralt doit découvrir pourquoi les jeunes femmes de Novigrad se changent en grenouilles.'],
  ['Evil wears many faces, as does justice. From land to sea, Geralt finds that where man and creature coexist, there is an unspoken rule-one where the skills of a witcher go beyond killing monsters. When a job at sea takes a bloody turn, Geralt is washed ashore on a strange new land. Taken in by local hunters, they discover a bargain to be had—a task for an indebted witcher and a share in the reward. But an omnipresent eye watches their every move, and Geralt is soon dragged into a conflict between the hunters and a mysterious clan known to kill humans. Created in close collaboration with CD PROJEKT RED!',
   'Le mal a bien des visages, la justice aussi. De la terre à la mer, Geralt découvre que là où l\'homme et la créature cohabitent règne une règle tacite, et que le métier de sorceleur ne se résume pas à tuer des monstres. Un contrat en mer tourne au carnage et le rejette sur un rivage inconnu. Recueilli par des chasseurs, il y voit un marché à conclure : une tâche pour un sorceleur endetté, une part de la récompense. Mais un œil omniprésent suit chacun de leurs gestes, et Geralt se retrouve pris dans le conflit qui oppose les chasseurs à un clan mystérieux, réputé tuer les humains.'],
  ['"A Night to Remember" is a pre-launch trailer for The Witcher 3: Wild Hunt released by Digic Pictures and CD PROJEKT RED on 14 May 2015. Similar to the Killing Monsters trailer, this cinematic told a short, yet engrossing story about Geralt hunting a bruxa.',
   '« A Night to Remember » est le trailer de lancement de The Witcher 3: Wild Hunt, réalisé par Digic Pictures et CD PROJEKT RED et sorti le 14 mai 2015. Comme le trailer Killing Monsters, cette cinématique raconte une histoire courte et prenante : Geralt y chasse une bruxa.'],
  ['Geralt acquires a taste for a simple life-good wine and good company. With Yennefer at his side, the routines of a witcher are eclipsed. But the stains of history are deep, and with blood and wine, every drop attracts those who want more.',
   'Geralt prend goût à une vie simple, faite de bon vin et de bonne compagnie. Yennefer à ses côtés, les habitudes du sorceleur s\'effacent. Mais les taches de l\'histoire sont tenaces, et avec le sang et le vin, chaque goutte attire ceux qui en veulent davantage.'],
  ['Geralt travels to a remote town where a vampire is rumored to be killing the townspeople. The bounty has amassed all manner of monster hunters—and among them is another witcher, from the school of the Bear, a fierce competitor for the reward.',
   'Geralt se rend dans une ville reculée où l\'on dit qu\'un vampire tue les habitants. La prime a attiré toutes sortes de chasseurs de monstres — et parmi eux un autre sorceleur, de l\'école de l\'Ours, rude concurrent pour la récompense.'],
  ['Ancient dwarven mines have attracted treasure hunters, and legend has it a horned beast is killing them. With no signs of an attack, Geralt surveys the lay of the land, but the mountains are deadly, and the mines even deadlier. And in the labyrinth of the dwarven caves, what remains is best left untouched.',
   'D\'anciennes mines naines attirent les chercheurs de trésors, et la légende veut qu\'une bête cornue les tue les uns après les autres. Sans trace d\'attaque, Geralt examine le terrain, mais la montagne est mortelle et les mines plus encore. Et dans le labyrinthe des galeries naines, mieux vaut ne pas déranger ce qui reste.'],
  ['Hide done',
   'Masquer ce qui est fait'],
  ['Mark “{t}” as done',
   'Marquer « {t} » comme fait'],
  ['Reset your The Witcher progress?',
   'Réinitialiser votre progression The Witcher ?'],
  ['Books and games timelines',
   'Les chronologies des livres et des jeux'],
  ['Sapkowski\'s books · CD Projekt RED\'s games and comics',
   'Les livres de Sapkowski · les jeux et les comics de CD Projekt RED'],
  ['Sapkowski\'s Timeline',
   'La chronologie de Sapkowski'],
  ['CD Projekt Red\'s Timeline',
   'La chronologie de CD Projekt RED'],
  ['The 2 timelines',
   'Les 2 chronologies'],
  /* « Fan translation available here » n'a plus de traduction : le lien ne
     paraît plus côté français, la nouvelle ayant une édition française.
     Voir SANS_LIEN dans traduire-witcher.mjs. */
  ['Watch on YouTube',
   'Regarder sur YouTube'],
  ['Every story of The Last Wish read',
   'Toutes les nouvelles du Dernier Vœu lues'],
  ['Child of Destiny',
   'Enfant-Surprise'],
  ['Every story of Sword of Destiny read',
   'Toutes les nouvelles de L\'Épée de la Providence lues'],
  ['The five novels of the saga read',
   'Les cinq romans de la saga lus'],
  ['White Wolf',
   'Le Loup Blanc'],
  ['The three main games played',
   'Les trois jeux principaux terminés'],
  ['Both Wild Hunt expansions played',
   'Les deux extensions de Wild Hunt terminées'],
  ['Adaptation of the short story from The Last Wish.',
   'Adaptation de la nouvelle du recueil Le Dernier Vœu.'],
  ['Adaptation of the chapters 14-15 of Season of Storms.',
   'Adaptation des chapitres 14-15 de La Saison des Orages.'],
  ['The game takes place concurrently to the saga. Chapters 1–2 happen concurrently to chapters 4–5 of Time of Contempt. Chapter 3 happens around chapter 3 and chapter 4 happens concurrently with chapter 7 of Baptism of Fire. Chapter 5 happens concurrently with chapters 6–8 and epilogue happens before chapter 9 of Lady of the Lake.',
   'Le jeu se déroule en parallèle de la saga. Les chapitres 1 et 2 se déroulent en même temps que les chapitres 4 et 5 du Temps du Mépris. Le chapitre 3 se situe autour du chapitre 3 et le chapitre 4 en même temps que le chapitre 7 du Baptême du Feu. Le chapitre 5 se déroule en même temps que les chapitres 6 à 8, et l\'épilogue avant le chapitre 9 de La Dame du Lac.'],
  ['The game states that the events of the last book happened 5 years prior to the game, this conflict with the books because the events happen in 1268 so it\'s only two years.',
   'Le jeu annonce que les événements du dernier livre remontent à 5 ans, ce qui contredit les livres : ils se déroulent en 1268, donc deux ans plus tôt seulement.'],
  ['If you\'re here it\'s either because you did some of the games and want to read the books or read the books and want to discover the games. Or maybe do both and complete the full timeline. This guide is spoiler free like the others.',
   'Si vous êtes ici, c\'est soit parce que vous avez fait certains des jeux et voulez lire les livres, soit parce que vous avez lu les livres et voulez découvrir les jeux. Ou peut-être les deux, pour compléter toute la chronologie. Ce guide est sans spoil, comme les autres.'],
  ['This guide works for first-time as well as replay or reread.',
   'Ce guide vaut pour une première fois comme pour une relecture ou une nouvelle partie.'],
  ['THE CALENDAR',
   'LE CALENDRIER'],
  ['The timeline documents important dates and events in the Witcher series, with the dates in human calendar are counted from the "Revival" (mentioned in Season of Storms) or the "Resurrectionem" (mentioned in Crossroads of Ravens).',
   'La chronologie recense les dates et les événements importants de la série The Witcher ; dans le calendrier humain, les dates sont comptées à partir de la « Renaissance » (mentionnée dans La Saison des Orages) ou de la « Resurrectionem » (mentionnée dans La Croisée des Corbeaux).'],
  ['In writing, the notations are written with a lower case "p" and upper case "R", such as "1215 post Resurrectionem" and "1 July 1245 p.R." However, it\'s yet to be seen how "before Revival/Resurrectionem" is written.',
   'À l\'écrit, la notation porte un « p » minuscule et un « R » majuscule, comme dans « 1215 post Resurrectionem » et « 1er juillet 1245 p.R. ». On ne sait pas encore, en revanche, comment s\'écrit « avant la Renaissance / Resurrectionem ».'],
  ['We do not know what the Resurrectionem is, neither do the characters in-universe, the author left it a mystery for everyone.',
   'On ne sait pas ce qu\'est la Resurrectionem, et les personnages ne le savent pas davantage : l\'auteur en a gardé le mystère pour tout le monde.'],
  ['Some events work better as a FLASHBACK for understanding, and are marked as such.',
   'Certains événements se comprennent mieux en FLASHBACK, et sont signalés comme tels.'],
  ['CANONICITY',
   'CANONICITÉ'],
  ['Everything of The Witcher is rooted in the same source material: the books by the Polish writer Andrzej Sapkowski. Years after Sapkowski ended his saga chronologically with The Lady of the Lake in 1999, the Polish developer CD Projekt RED made the first game called The Witcher. Theoretically, the first game takes place after the last book, but the video games are not an official sequel.',
   'Tout The Witcher vient d\'une même source : les livres de l\'écrivain polonais Andrzej Sapkowski. Des années après que Sapkowski a refermé sa saga avec La Dame du Lac en 1999, le studio polonais CD Projekt RED a fait le premier jeu, The Witcher. En théorie, ce premier jeu se déroule après le dernier livre, mais les jeux vidéo n\'en sont pas une suite officielle.'],
  ['Yet we see the same characters, and there are references to events from the books.',
   'On y retrouve pourtant les mêmes personnages, et des renvois aux événements des livres.'],
  ['In any case, Sapkowski is not a fan of video games (generally speaking) and it is therefore unlikely we’ll ever see a book that takes place during or in between one of the video games. This also gives CD Projekt Red the freedom to deviate from the books.',
   'De toute façon, Sapkowski n\'aime pas les jeux vidéo (en général), et il est donc peu probable qu\'un livre se déroule un jour pendant ou entre deux jeux. Cela laisse aussi à CD Projekt RED la liberté de s\'écarter des livres.'],
  ['Some little things conflict but otherwise you can read the books and then play the games.',
   'Quelques petites choses se contredisent, mais à cela près vous pouvez lire les livres puis jouer aux jeux.'],
  ['The comics follow their own canonicity since the games have different choices and endings.',
   'Les comics ont leur propre canonicité, les jeux ayant des choix et des fins différents.'],
  ['Netflix universe',
   'Univers Netflix'],
  ['adaptation of the books in it\'s own universe.',
   'adaptation des livres dans son propre univers.'],
  ['The Hexer film and series',
   'Le film et la série Le Sorceleur'],
  ['Board games, mobile games, web games, GWENT games and paper RPG',
   'Jeux de plateau, jeux mobiles, jeux web, jeux GWENT et jeu de rôle papier'],
  // les trois décomptes de la page (barre du bas, bande, colonnes), restés en anglais jusqu'au 21 septembre 2026
  ['too hard to fit in the timeline.',
   'trop difficiles à placer dans la chronologie.'],
  ['Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World and The Witcher are trademarks of their respective owners; Chronologeek is an independent fan project.',
   'Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World et The Witcher sont des marques de leurs ayants droit respectifs ; Chronologeek est un projet de fan indépendant.'],
  ['. Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World and The Witcher are trademarks of their respective owners; Chronologeek is an independent fan project.',
   '. Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World et The Witcher sont des marques de leurs ayants droit respectifs ; Chronologeek est un projet de fan indépendant.'],
  ['. Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World and The Witcher are trademarks of their respective owners; Chronologeek is an independent fan project.',
   '. Star Wars, Marvel, DC, Avatar Legends, Star Trek, The Walking Dead, Dragon Age, Assassin’s Creed, Jurassic World et The Witcher sont des marques de leurs ayants droit respectifs ; Chronologeek est un projet de fan indépendant.'],
  ['Sapkowski\'s books · CD Projekt RED\'s games and comics — two parallel timelines, side by side, spoiler-free.',
   'Les livres de Sapkowski · les jeux et les comics de CD Projekt RED — deux chronologies parallèles, côte à côte, sans spoil.'],
  ['54 / 54 shown',
   '54 / 54 affichées'],
  ['Check off what you\'ve read and played — your progress is saved.',
   'Cochez ce que vous avez lu et joué — votre progression est sauvegardée.'],
  ['This story describes the circumstances of Geralt and Yennefer&#x27;s first meeting.',
   'Cette nouvelle raconte les circonstances de la première rencontre entre Geralt et Yennefer.'],
  ['The story begins with Geralt being clean-shaven, washed and nicely clothed by the servants and castellan Haxo of the royal family&#x27;s castle in Cintra. Cintra&#x27;s crown-princess, Pavetta, has turned fifteen years old and, as is the custom, contenders for her hand have turned up by the dozen. Geralt asks the castellan, Haxo, why he was invited and is told that the queen very much wants to ensure that Cintra becomes allied with Skellige and that a witchers services are likely required to ensure this outcome.',
   'L\'histoire commence avec Geralt rasé de près, lavé et vêtu par les serviteurs et le castellan Haxo, au château de la famille royale de Cintra. Pavetta, princesse héritière de Cintra, vient d\'avoir quinze ans et, comme le veut la coutume, les prétendants à sa main sont arrivés par dizaines. Geralt demande au castellan pourquoi il a été convié : la reine tient à ce que Cintra s\'allie à Skellige, et les services d\'un sorceleur seront sans doute nécessaires pour que cette alliance se fasse.'],
  ['In the story we learn more about Geralt&#x27;s history with the sorceress Yennefer.',
   'On y apprend un peu plus sur le passé de Geralt avec la magicienne Yennefer.'],
  ['In search of a reward, Geralt brings the carcass of a slain creature to a small town where he is told it may be of use to the local sorcerer - but the mage isn&#x27;t who he is alleged to be. In hiding for his life, he requests Geralt&#x27;s help in slaying the monster who seeks to murder him - a young woman said to have been born under the Curse of the Black Sun - a prophecy of inborn evil. He declares that she is more a monster than the creature presented before him. Geralt later encounters the woman, who asserts that it is the sorcerer who is the true monster - committing unspeakable crimes at the behest of his superstitious beliefs. With the boundaries blurred between the evil that is done and the evil done in return, Geralt is met with a quandary. The face of evil is ever-changing and his verdict, whether by choice or by force, can only lead to tragedy.',
   'En quête d\'une récompense, Geralt apporte la dépouille d\'une créature dans une petite ville, où l\'on prétend que le magicien du cru pourrait en avoir l\'usage — mais le mage n\'est pas celui qu\'il dit être. Terré pour sauver sa vie, il demande à Geralt de tuer le monstre qui veut sa mort : une jeune femme née, dit-on, sous la Malédiction du Soleil noir, une prophétie de mal inné. Il la déclare plus monstrueuse que la créature posée devant lui. Geralt croise ensuite la jeune femme, pour qui le véritable monstre est le magicien, coupable de crimes indicibles au nom de ses croyances. La frontière entre le mal commis et le mal rendu s\'effaçant, Geralt se retrouve devant un dilemme : le visage du mal ne cesse de changer, et son verdict, choisi ou imposé, ne peut mener qu\'à la tragédie.'],
  ['Work is hard to come by for Geralt and with Dandelion, not a subject for his rhymes or ballads. As they travel to the edge of the known world, townsfolk speak of many stories but it seems that&#x27;s all they are—recitals of monsters and superstition—until a man follows Geralt with news of a devil scavenging the local fields. Rid the beast, but under no condition is he to be killed. Only how can Geralt hunt the creature, for there is no such things as devils...',
   'Le travail se fait rare pour Geralt, et avec Jaskier, ce n\'est pas un sujet de ballade. Tandis qu\'ils gagnent le bout du monde connu, les villageois content mille histoires qui ne sont que cela — récits de monstres et superstitions — jusqu\'à ce qu\'un homme rattrape Geralt : un diable ravage les champs des environs. Qu\'il en débarrasse le pays, mais sous aucun prétexte il ne doit le tuer. Reste à savoir comment chasser une créature qui n\'existe pas, puisque les diables n\'existent pas…'],
  ['The desire for power unleashes chaos and seals a new destiny in this graphic novel adaptation of Andrzej Sapkowski&#x27;s short story. Driven by unhealthy curiosity, Dandelion breaks a magic seal and unleashes a djinn whom he hopes will grant his wishes. Instead, the creature attacks him, leaving him with wounds only a mage can heal. Geralt rushes the bard to a nearby town, but in a city where casting spells carries heavy penalties, there is only one sorceress who resides—Yennefer of Vengerberg. Despite her beauty, grace, and zeal, can she be trusted? With the djinn set loose, Geralt is at the mercy of magic. And as a struggle for power and control begins, wishes are made, but whose are being granted?',
   'La soif de pouvoir déchaîne le chaos et scelle un destin, dans cette adaptation en bande dessinée de la nouvelle d\'Andrzej Sapkowski. Poussé par une curiosité malsaine, Jaskier brise un sceau magique et libère un djinn dont il espère qu\'il exaucera ses vœux. La créature l\'attaque et le laisse blessé au point que seule la magie peut le sauver. Geralt conduit le barde jusqu\'à la ville voisine, où lancer un sort coûte cher et où ne réside qu\'une seule magicienne : Yennefer de Vengerberg. Malgré sa beauté, sa grâce et son ardeur, peut-on lui faire confiance ? Le djinn lâché dans la nature, Geralt est à la merci de la magie. Et tandis que s\'engage une lutte de pouvoir, des vœux sont formulés — mais à qui sont-ils accordés ?'],
  ['Geralt is invited to a banquet at the Kingdom of Cintra. The Princess has come of age and suitors prepare to present themselves for her hand in marriage. Wary of the Queen&#x27;s invitation, Geralt attends the dinner with caution. When a mysterious uninvited guest, bearing the armor of a knight enters the hall, a bold declaration and a shocking revelation ignites the party into chaos and uproar.',
   'Geralt est convié à un banquet au royaume de Cintra. La princesse est en âge de se marier, et les prétendants s\'apprêtent à demander sa main. Méfiant devant l\'invitation de la reine, Geralt s\'installe à table sur ses gardes. Lorsqu\'un convive mystérieux, en armure de chevalier, entre dans la salle, une déclaration audacieuse et une révélation renversante jettent le banquet dans le chaos.'],
  ['Sin manifests into bloodlust in this graphic novel adaptation of Andrzej Sapkowski&#x27;s original short story. Geralt pursues a proclamation from a king of a bloodthirsty monster plaguing his palace. A hefty reward is offered to cure the beast, but not to kill it, for the king holds a secret—what lies beneath the palace is beyond the spawn of evil. Tried and failed by charlatans, Geralt sets out to claim the bounty—by decree of the king or by the pleas of those who wish the creature dead.',
   'Le péché se mue en soif de sang dans cette adaptation en bande dessinée de la nouvelle d\'Andrzej Sapkowski. Geralt répond à la proclamation d\'un roi dont le palais est hanté par un monstre assoiffé de sang. La récompense est lourde, mais elle va à qui guérira la bête, pas à qui la tuera : le roi garde un secret, et ce qui dort sous le palais n\'est pas qu\'une engeance du mal. Après l\'échec des charlatans, Geralt part réclamer la prime — par décret du roi ou par les supplications de ceux qui veulent la créature morte.'],
  ['While still enjoying the inn, the patrons, after listening to Dandelion singing his first ballad, wish to hear another story. This tale, set one year after Geralt tamed the striga the first time, starts in a rather unoriginal way — in (Vizima&#x27;s) prison. The twist is that, this time, Geralt is the person visiting someone, not the one behind bars. So who is the unfortunate fellow? It is Dandelion of course, Geralt&#x27;s old pal, and once again he has gotten himself into trouble. Because Geralt is his friend, the task of getting the bard off the hook falls to the witcher, once again (&quot;... I promise Geralt, that&#x27;s the last time, or almost the last time, really!&quot;).',
   'Toujours à l\'auberge, les clients, après la première ballade de Jaskier, en réclament une autre. Ce récit-là, situé un an après que Geralt a maîtrisé la strige, commence de façon fort banale : en prison, à Vizima. À ceci près que cette fois, Geralt est celui qui rend visite, et non celui qui est derrière les barreaux. Le malheureux, c\'est Jaskier, bien sûr, encore une fois dans de mauvais draps — et c\'est au sorceleur, en ami, de l\'en sortir.'],
  ['The year was 1271. The place - Vergen. The moment - portentous. King Henselt&#x27;s long siege had finally ended. Life was slowly returning to normal - or as &quot;normal&quot; as it could be in a city where humans, dwarves and elves lived side by side and in harmony, the whole powder keg led by a maiden... And not just any maiden, mind you, but the virgin and heroine Saskia, until recently known as the Dragonslayer, before she was revealed to be a dragon herself.',
   'Nous sommes en 1271, à Vergen, et le moment est de ceux qui comptent. Le long siège du roi Henselt vient de prendre fin et la vie reprend son cours — autant qu\'elle le peut dans une ville où humains, nains et elfes vivent côte à côte, ce baril de poudre étant mené par une jeune femme. Et pas n\'importe laquelle : l\'héroïne Saskia, dite la Tueuse de dragons, jusqu\'à ce qu\'on découvre qu\'elle en était un.'],
  ['In The Witcher, it&#x27;s an original tale featuring the iconic witcher, Geralt! Created in close collaboration with CD PROJEKT RED!',
   'Un récit inédit mettant en scène le sorceleur Geralt, créé en étroite collaboration avec CD PROJEKT RED.'],
  ['&quot;A Night to Remember&quot; is a pre-launch trailer for The Witcher 3: Wild Hunt released by Digic Pictures and CD PROJEKT RED on 14 May 2015. Similar to the Killing Monsters trailer, this cinematic told a short, yet engrossing story about Geralt hunting a bruxa.',
   '« A Night to Remember » est le trailer de lancement de The Witcher 3: Wild Hunt, réalisé par Digic Pictures et CD PROJEKT RED et sorti le 14 mai 2015. Comme le trailer Killing Monsters, cette cinématique raconte une histoire courte et prenante : Geralt y chasse une bruxa.'],
  ['Sapkowski&#x27;s books · CD Projekt RED&#x27;s games and comics',
   'Les livres de Sapkowski · les jeux et les comics de CD Projekt RED'],
  ['Sapkowski&#x27;s Timeline',
   'La chronologie de Sapkowski'],
  ['CD Projekt Red&#x27;s Timeline',
   'La chronologie de CD Projekt RED'],
  ['The game states that the events of the last book happened 5 years prior to the game, this conflict with the books because the events happen in 1268 so it&#x27;s only two years.',
   'Le jeu annonce que les événements du dernier livre remontent à 5 ans, ce qui contredit les livres : ils se déroulent en 1268, donc deux ans plus tôt seulement.'],
  ['If you&#x27;re here it&#x27;s either because you did some of the games and want to read the books or read the books and want to discover the games. Or maybe do both and complete the full timeline. This guide is spoiler free like the others.',
   'Si vous êtes ici, c\'est soit parce que vous avez fait certains des jeux et voulez lire les livres, soit parce que vous avez lu les livres et voulez découvrir les jeux. Ou peut-être les deux, pour compléter toute la chronologie. Ce guide est sans spoil, comme les autres.'],
  ['The timeline documents important dates and events in the Witcher series, with the dates in human calendar are counted from the &quot;Revival&quot; (mentioned in Season of Storms) or the &quot;Resurrectionem&quot; (mentioned in Crossroads of Ravens).',
   'La chronologie recense les dates et les événements importants de la série The Witcher ; dans le calendrier humain, les dates sont comptées à partir de la « Renaissance » (mentionnée dans La Saison des Orages) ou de la « Resurrectionem » (mentionnée dans La Croisée des Corbeaux).'],
  ['In writing, the notations are written with a lower case &quot;p&quot; and upper case &quot;R&quot;, such as &quot;1215 post Resurrectionem&quot; and &quot;1 July 1245 p.R.&quot; However, it&#x27;s yet to be seen how &quot;before Revival/Resurrectionem&quot; is written.',
   'À l\'écrit, la notation porte un « p » minuscule et un « R » majuscule, comme dans « 1215 post Resurrectionem » et « 1er juillet 1245 p.R. ». On ne sait pas encore, en revanche, comment s\'écrit « avant la Renaissance / Resurrectionem ».'],
  ['adaptation of the books in its own universe.',
   'adaptation des livres dans son propre univers.'],
  ['Sapkowski&#x27;s books · CD Projekt RED&#x27;s games and comics — two parallel timelines, side by side, spoiler-free.',
   'Les livres de Sapkowski · les jeux et les comics de CD Projekt RED — deux chronologies parallèles, côte à côte, sans spoil.'],
  ['Check off what you&#x27;ve read and played — your progress is saved.',
   'Cochez ce que vous avez lu et joué — votre progression est sauvegardée.'],
];

/* Aucun gabarit : cette page n'a ni sous-items d'épisodes ni titres de
   phase. La liste existe parce que le script l'attend. */
export const W_GABARITS = [];

/* Titre par identifiant : voir le commentaire du generateur. Une oeuvre sans
   edition francaise garde le sien — c'est la regle de Niko, et c'est aussi ce
   que dit son badge VO. */
export const W_TITRES = {
  'w-road': 'La Route d\'où l\'on ne revient pas',
  'w-crossroads': 'La Croisée des Corbeaux',
  'w-grain': 'Un grain de vérité',
  'w-lesser': 'Le Moindre Mal',
  'w-edge': 'Le Bout du monde',
  'w-lastwish': 'Le Dernier Vœu',
  'w-price': 'Une question de prix',
  'w-witcher': 'Le Sorceleur',
  'w-voice': 'La Voix de la raison',
  'w-bounds': 'Les limites du possible',
  'w-shard': 'Éclat de glace',
  'w-flame': 'Le Feu éternel',
  'w-sacrifice': 'Une once d\'abnégation',
  'w-sword': 'L\'Épée de la Providence',
  'w-more': 'Quelque chose en plus',
  'w-blood': 'Le Sang des Elfes',
  'w-contempt': 'Le Temps du Mépris',
  'w-baptism': 'Le Baptême du Feu',
  'w-tower': 'La Tour de l\'Hirondelle',
  'w-lady': 'La Dame du Lac',
  'w-storms': 'La Saison des Orages',
  'wc-grain': 'The Witcher : Un grain de vérité',
  'wc-lesser': 'The Witcher: The Lesser Evil',
  'wc-glass': 'The Witcher : La Maison de Verre',
  'wc-kiddo': 'Kiddo',
  'wc-edge': 'The Edge of the World',
  'wc-lastwish': 'The Last Wish',
  'wc-fox': 'The Witcher : Les Filles-Renardes',
  'wc-price': 'A Question of Price',
  'wc-witcher': 'The Witcher',
  'wc-reasons': 'The Witcher : Raisons d’État',
  'wg-thronebreaker': 'Thronebreaker: The Witcher Tales',
  'wg-w1': 'The Witcher',
  'wg-neutrality': 'Le Prix de la Neutralité',
  'wg-sideeffects': 'Effets secondaires',
  'wg-w2': 'The Witcher 2: Assassins of Kings',
  'wc-conscience': 'The Witcher: Matters of Conscience',
  'wc-killing': 'The Witcher: Killing Monsters',
  'wv-killing': 'Killing Monsters',
  'wg-w3': 'The Witcher 3: Wild Hunt',
  'wg-hos': 'Hearts of Stone',
  'wc-crows': 'The Witcher : La Malédiction des corbeaux',
  'wc-flesh': 'The Witcher : De chair et de flamme',
  'wc-lament': 'The Witcher : La Complainte de la sorcière',
  'wc-wolves': 'The Witcher : La Ballade des deux loups',
  'wc-woods': 'The Witcher: Once Upon a Time in the Woods',
  'wc-frog': 'The Witcher: Frog Kiss',
  'wc-wild': 'The Witcher: Wild Animals',
  'wg-baw': 'Blood and Wine',
  'wv-night': 'A Night to Remember',
  'wc-corvo': 'The Witcher: Corvo Bianco',
  'wc-fading': 'The Witcher : Souvenirs lointains',
  'wc-bear': 'The Witcher: The Bear and the Butterfly',
  'wc-bloodstone': 'The Witcher: Blood Stone',
};
