/* ═══ AVATAR : LE SEUL UNIVERS QU'IL FAUT VRAIMENT TRADUIRE ═════════
   Les trois autres timelines et le Dossier ne sont pas traduits mais
   retrouvés : la racine du site est anglaise, `/fr/` française, et les
   deux sont tenues à parité, donc l'anglais existe déjà, relu et en
   ligne. Avatar est l'exception. `avatar.html` à la racine est encore
   la page française non traduite, et il n'y a pas de `fr/avatar.html` :
   il n'existe aucune source anglaise à reprendre.

   Cette table est donc la seule de tout le dispositif où l'anglais est
   écrit plutôt qu'extrait. Chaque ligne part au rapport de relecture,
   comme les douze phrases de `TRADUCTIONS` dans `traduire.mjs`.

   TROIS RÈGLES, DANS CET ORDRE.

   1. Un titre d'œuvre n'est pas traduit, il est retrouvé. Tout ce que
      cette timeline liste est américain : « La Promesse » s'appelle
      « The Promise », « Les Aventures Perdues » « The Lost Adventures ».
      Rendre le titre original n'est pas une traduction, c'est enlever
      la sienne. Les mentions de recueil suivent le même chemin.
   2. Les synopsis sont de Niko, et se traduisent au plus près. Pas de
      raccourci, pas d'ajout, pas d'« amélioration » : sa phrase dit ce
      qu'elle dit, dans l'ordre où elle le dit.
   3. Ce qui vaut pour les deux langues n'est pas traduit, il est
      déclaré identique, dans la liste du dessous.

   CE QUI DISPARAÎT EN ANGLAIS, ET POURQUOI. Deux mentions du français
   ne survivent pas au passage, pour la raison qui vaut déjà au badge
   VO du Dossier : elles ne disent rien à qui lit justement l'anglais.

   Le nom du recueil français, d'abord. « Les Héroïnes de la Team
   Avatar » et « Feu et Trésor Familial » sont des recueils de
   l'éditeur français ; en anglais, Katara and the Pirate's Silver,
   Suki, Alone et les autres ont paru chacun de leur côté. Le titre
   anglais reste donc seul, sans préfixe qui n'existe pas.

   La phrase « VF dans le recueil… », ensuite, qui dit où trouver la
   version française d'une histoire courte. Elle tombe pour la même
   raison. Les recueils qui existent des deux côtés, eux, restent :
   « Aussi disponible dans le recueil Team Avatar Tales » devient
   « Also available in the Team Avatar Tales collection », parce que
   ce recueil-là, un lecteur anglophone peut l'acheter.

   ══════════════════════════════════════════════════════════════════ */

/* Ce qui s'écrit pareil des deux côtés : titres jamais traduits en
   français, repères de calendrier, et les valeurs de données que le
   traducteur croise en chemin. Déclarées, elles ne repartent pas au
   rapport de relecture — il n'y a rien à y relire. */
export const AVATAR_IDENTIQUES = [
  /* Le nom de l'univers, renommé pour ne plus se confondre avec les films
     de James Cameron. Il ne se traduit pas. */
  "Avatar Legends",
  "Chronicles of the Avatar 3 : The Dawn of Yangchen",
  "483 BG",
  "vo",
  "Chronicles of the Avatar 4 : The Legacy of Yangchen",
  "482 BG",
  "Chronicles of the Avatar 1 : The Rise of Kyoshi",
  "296 BG",
  "Chronicles of the Avatar 2 : The Shadow of Kyoshi",
  "295 BG",
  "Chronicles of the Avatar 5 : The Reckoning of Roku",
  "66 BG",
  "Chronicles of the Avatar 6 : The Awakening of Roku",
  "63 BG",
  "99 AG",
  "100 AG",
  "vf",
  "The Kyoshi Warriors",
  "Escape from the Spirit World",
  "Earth & Water (Comics Giveaway Day 2026)",
  "~55 BG",
  "City of Echoes",
  "101 AG",
  "102 AG",
  "Matcha Makers (Free Comic Book Day 2021)",
  "112 AG",
  "124 AG",
  "~158 AG",
  "Patterns in Time : Skyscrapers",
  "Patterns in Time : Weaver's Ball",
  "~167 AG",
  "170 AG",
  "171 AG",
  "Kya and the Secret of the Sand",
  "~172 AG",
  "Patterns in Time : Cat-Owl's Cradle",
  "~173 AG",
  "174 AG",
  "Lost Pets (Free Comic Book Day 2018)",
  "An Avatar's Chronicle",
  "Legacy of the Fire Nation",
  "~174 AG",
  "Mystery of Penquan Island",
  "Patterns in Time : Clearing the Air",
  "Patterns in Time : A Change in the Wind",
  "avatar",
  "br",
];

/* Les phrases écrites. Chacune part dans A-RELIRE-EN.md. */
export const AVATAR_TRADUCTIONS = [
  ["ÈRE DE YANGCHEN",
   "THE YANGCHEN ERA"],
  ["Jeune Avatar hantée par les souvenirs de ses vies antérieures, Yangchen navigue entre diplomatie et complots dans la ville corrompue de Bin-Er.",
   "A young Avatar haunted by the memories of her past lives, Yangchen navigates diplomacy and conspiracy in the corrupt city of Bin-Er."],
  ["Yangchen affronte les conséquences de ses choix et un complot qui menace l'équilibre entre les nations.",
   "Yangchen faces the consequences of her choices, and a plot that threatens the balance between the nations."],
  ["ÈRE DE KYOSHI",
   "THE KYOSHI ERA"],
  ["Servante ignorant qu'elle est l'Avatar, Kyoshi fuit après une tragédie et apprend à survivre auprès de hors-la-loi. L'origine brutale de la plus légendaire des Avatars.",
   "A servant who has no idea she is the Avatar, Kyoshi flees after a tragedy and learns to survive among outlaws. The brutal origin of the most legendary Avatar of them all."],
  ["Deux ans plus tard, Kyoshi est convoquée à la Nation du Feu, où une menace venue du Monde des Esprits couve derrière la politique.",
   "Two years later, Kyoshi is summoned to the Fire Nation, where a threat from the Spirit World is brewing behind the politics."],
  ["ÈRE DE ROKU",
   "THE ROKU ERA"],
  ["Le jeune Roku accepte une mission secrète du prince Sozin et découvre des agendas cachés sur une île isolée, aux côtés de son nouvel ami Gyatso.",
   "Young Roku takes on a secret mission from Prince Sozin and uncovers hidden agendas on a remote island, alongside his new friend Gyatso."],
  ["Impatient de maîtriser l'État d'Avatar, Roku canalise l'énergie du solstice d'hiver — et déclenche le chaos sur l'Île du Croissant.",
   "Impatient to master the Avatar State, Roku channels the energy of the winter solstice — and unleashes chaos on Crescent Island."],
  ["LIVRE 1 : L'EAU",
   "BOOK ONE : WATER"],
  ["GUERRE DE CENT ANS",
   "HUNDRED YEAR WAR"],
  ["Avatar : Le Dernier Maître de l'Air",
   "Avatar : The Last Airbender"],
  ["Saison 1 Épisodes 1-10",
   "Season 1 Episodes 1-10"],
  ["Saison 1 Épisodes 11-16",
   "Season 1 Episodes 11-16"],
  ["Les Aventures Perdues : Reliques",
   "The Lost Adventures : Relics"],
  ["Histoire courte du recueil Les Aventures Perdues (The Lost Adventures).",
   "Short story from The Lost Adventures collection."],
  ["Saison 1 Épisodes 17-20",
   "Season 1 Episodes 17-20"],
  ["LIVRE 2 : LA TERRE",
   "BOOK TWO : EARTH"],
  ["Suki et les guerrières Kyoshi rejoignent l'armée du Royaume de la Terre.",
   "Suki and the Kyoshi Warriors join the Earth Kingdom army."],
  ["Saison 2 Épisodes 1-9",
   "Season 2 Episodes 1-9"],
  ["Les Héroïnes de la Team Avatar : Katara et l'Argent des Pirates",
   "Katara and the Pirate's Silver"],
  ["Séparée du groupe après une embuscade, Katara doit s'allier à des pirates pour retrouver ses amis. VF dans le recueil Les Héroïnes de la Team Avatar.",
   "Separated from the group after an ambush, Katara has to side with pirates to find her friends again."],
  ["Les Aventures Perdues : Sokka l'Avatar",
   "The Lost Adventures : Sokka the Avatar"],
  ["Les Aventures Perdues : Séparés, Nous Chutons",
   "The Lost Adventures : Divided We Fall"],
  ["Saison 2 Épisodes 10-20",
   "Season 2 Episodes 10-20"],
  ["Histoires animées interactives à regarder gratuitement sur YouTube, pendant le coma d'Aang entre les Livres 2 et 3.",
   "Interactive animated stories to watch for free on YouTube, set during Aang's coma between Books Two and Three."],
  ["Regarder sur YouTube",
   "Watch on YouTube"],
  ["Les Aventures Perdues : C'est Bien Naturel",
   "The Lost Adventures : It's Only Natural"],
  ["Les Aventures Perdues : Retour à la Maison",
   "The Lost Adventures : Going Home Again"],
  ["Les Aventures Perdues : Le Pont",
   "The Lost Adventures : The Bridge"],
  ["LIVRE 3 : LE FEU",
   "BOOK THREE : FIRE"],
  ["Saison 3 Épisodes 1-2",
   "Season 3 Episodes 1-2"],
  ["Les Aventures Perdues : Soldat Feu",
   "The Lost Adventures : Private Fire"],
  ["Saison 3 Épisodes 3-6",
   "Season 3 Episodes 3-6"],
  ["Les Aventures Perdues : L'Homme Explosif Dans un Train",
   "The Lost Adventures : Combustion Man on a Train"],
  ["Saison 3 Épisodes 8-13",
   "Season 3 Episodes 8-13"],
  ["Les Aventures Perdues : L'Epoque des Dragons",
   "The Lost Adventures : Dragon Days"],
  ["Les Héroïnes de la Team Avatar : Suki, Seule",
   "Suki, Alone"],
  ["Prisonnière à la Roche Bouillante, Suki organise en secret un jardin — et une rébellion — parmi les détenus. VF dans le recueil Les Héroïnes de la Team Avatar.",
   "Imprisoned at the Boiling Rock, Suki secretly grows a garden — and a rebellion — among the inmates."],
  ["Les Aventures Perdues : L'Amour est un Champ de Bataille",
   "The Lost Adventures : Love Is a Battlefield"],
  ["Saison 3 Épisodes 15-19",
   "Season 3 Episodes 15-19"],
  ["Les Aventures Perdues : Bumi contre Toph, Premier Round",
   "The Lost Adventures : Bumi vs. Toph, Round One"],
  ["Saison 3 Épisodes 20-21",
   "Season 3 Episodes 20-21"],
  ["ÈRE DE AANG",
   "THE AANG ERA"],
  ["Roman jeunesse de l'univers Avatar Legends, entre esprits et mystères.",
   "A young readers novel set in the Avatar Legends universe, between spirits and mysteries."],
  ["La Promesse 1-3",
   "The Promise 1-3"],
  ["Aang et Zuko s'opposent sur le sort des colonies de la Nation du Feu — la naissance douloureuse d'un nouveau monde après la guerre.",
   "Aang and Zuko clash over the fate of the Fire Nation colonies — the painful birth of a new world after the war."],
  ["Rebond (Free Comic Book Day 2012)",
   "Rebound (Free Comic Book Day 2012)"],
  ["Aussi disponible dans le recueil Team Avatar Tales",
   "Also available in the Team Avatar Tales collection"],
  ["La Recherche 1-3",
   "The Search 1-3"],
  ["Zuko part enfin à la recherche de sa mère Ursa, accompagné d'une Azula imprévisible. La vérité l'attend dans une vallée peuplée d'esprits.",
   "Zuko finally sets out to find his mother Ursa, with an unpredictable Azula in tow. The truth is waiting for him in a valley full of spirits."],
  ["Fumée et Ombre 1",
   "Smoke and Shadow 1"],
  ["Zuko rentre dans une Nation du Feu rongée par la peur : la Société de la Nouvelle Ozai complote et des enfants disparaissent, enlevés par les mystérieux Kemurikage.",
   "Zuko comes home to a Fire Nation eaten away by fear: the New Ozai Society is plotting and children are disappearing, taken by the mysterious Kemurikage."],
  ["Le Désaccord 1-3",
   "The Rift 1-3"],
  ["Aang veut honorer un festival oublié des Nomades de l'Air, mais découvre une raffinerie sur une terre sacrée — dirigée par le père de Toph.",
   "Aang sets out to honor a forgotten Air Nomad festival, but finds a refinery on sacred ground — run by Toph's father."],
  ["Fumée et Ombre 2-3",
   "Smoke and Shadow 2-3"],
  ["La traque des Kemurikage s'intensifie — Zuko doit choisir entre la peur et la confiance, tandis qu'Azula tire les ficelles dans l'ombre.",
   "The hunt for the Kemurikage intensifies — Zuko has to choose between fear and trust, while Azula pulls the strings from the shadows."],
  ["Nord et Sud 1-3",
   "North and South 1-3"],
  ["Katara et Sokka rentrent au Pôle Sud et découvrent leur tribu transformée par la modernité — et convoitée par des intérêts étrangers.",
   "Katara and Sokka return to the South Pole and find their tribe transformed by modernity — and coveted by foreign interests."],
  ["Coquillages (Free Comic Book Day 2014)",
   "Shells (Free Comic Book Day 2014)"],
  ["Sœurs (Free Comic Book Day 2013)",
   "Sisters (Free Comic Book Day 2013)"],
  ["Feu et Trésor Familial : Azula Face au Temple des Esprits",
   "Azula in the Spirit Temple"],
  ["Seule et en fuite, Azula arrive dans un temple mystérieux où des esprits la confrontent à ses souvenirs et à ses choix. VF dans le recueil Feu et Trésor Familial.",
   "Alone and on the run, Azula reaches a mysterious temple where spirits confront her with her memories and her choices."],
  ["Feu et Trésor Familial : Les Cendres de l'Académie",
   "Ashes of the Academy"],
  ["Mai est nommée à la tête de la réforme de l'éducation de la Nation du Feu — entre souvenirs d'Azula et menaces des loyalistes. VF dans le recueil Feu et Trésor Familial.",
   "Mai is put in charge of reforming Fire Nation education — between memories of Azula and threats from the loyalists."],
  ["Déséquilibre 1-3",
   "Imbalance 1-3"],
  ["À Cranefish Town, Team Avatar affronte une montée des tensions entre maîtres et non-maîtres qui annonce les conflits de l'ère de Korra.",
   "In Cranefish Town, Team Avatar faces rising tensions between benders and non-benders that foreshadow the conflicts of the Korra era."],
  ["Les Héroïnes de la Team Avatar : L'Académie de la Maîtrise du Métal de Toph Beifong",
   "Toph Beifong's Metalbending Academy"],
  ["Toph a ouvert la première académie de maîtrise du métal, mais ses élèves peinent — et l'inspiration lui manque. VF dans le recueil Les Héroïnes de la Team Avatar.",
   "Toph has opened the first metalbending academy, but her students are struggling — and she is short on inspiration."],
  ["Feu et Trésor Familial : La Chasseuse de Primes et le Maître du Thé",
   "The Bounty Hunter and the Tea Brewer"],
  ["June la chasseuse de primes accepte un contrat qui la mène droit au salon de thé d'Iroh. VF dans le recueil Feu et Trésor Familial.",
   "June the bounty hunter takes a contract that leads her straight to Iroh's tea shop."],
  ["Avatar Aang : Le Dernier Maître de l'Air",
   "Aang : The Last Airbender"],
  ["Livre-objet : Aang transmet souvenirs et reliques à son fils Tenzin.",
   "An in-universe book: Aang passes his memories and relics on to his son Tenzin."],
  ["ÈRE DE KORRA",
   "THE KORRA ERA"],
  ["Amies pour la Vie (Free Comic Book Day 2016)",
   "Friends for Life (Free Comic Book Day 2016)"],
  ["Aussi disponible dans le recueil Patterns in Time",
   "Also available in the Patterns in Time collection"],
  ["La Légende de Korra - Livre 1 : L'Air",
   "The Legend of Korra - Book One : Air"],
  ["La Légende de Korra - Livre 2 : Les Esprits",
   "The Legend of Korra - Book Two : Spirits"],
  ["La Légende de Korra - Livre 3 : Le Changement",
   "The Legend of Korra - Book Three : Change"],
  ["La Légende de Korra - Livre 4 : L'Équilibre",
   "The Legend of Korra - Book Four : Balance"],
  ["Guerres de Territoires 1-3",
   "Turf Wars 1-3"],
  ["Suite directe de la série : Korra et Asami reviennent du Monde des Esprits et affrontent un caïd qui exploite le nouveau portail spirituel.",
   "A direct sequel to the series: Korra and Asami come back from the Spirit World and take on a crime boss cashing in on the new spirit portal."],
  ["Livre-objet retraçant le voyage de Korra, annoté de sa main.",
   "An in-universe book retracing Korra's journey, annotated in her own hand."],
  ["Les Ruines de l'Empire 1-3",
   "Ruins of the Empire 1-3"],
  ["À la veille d'élections historiques dans le Royaume de la Terre, Kuvira peut-elle être rachetée ?",
   "On the eve of historic elections in the Earth Kingdom, can Kuvira be redeemed?"],
  ["Livre-objet : Iroh partage souvenirs et sagesse avec Zuko.",
   "An in-universe book: Iroh shares his memories and his wisdom with Zuko."],
  ["Histoire courte de l'ère Korra.",
   "A short story from the Korra era."],
  ["Timeline Chronologique",
   "Chronological Timeline"],
  ["Séries animées · Comics · Livres",
   "Animation · Comics · Books"],
  ["Effacer toute ta progression Avatar Legends ? Cette action est définitive.",
   "Erase all your Avatar Legends progress? This cannot be undone."],
  ["LIVRE",
   "BOOK"],
  ["Maître de l'Eau",
   "Waterbending Master"],
  ["Livre 1 : L'Eau terminé",
   "Book One : Water completed"],
  ["Maître de la Terre",
   "Earthbending Master"],
  ["Livre 2 : La Terre terminé",
   "Book Two : Earth completed"],
  ["Maître du Feu",
   "Firebending Master"],
  ["Livre 3 : Le Feu terminé",
   "Book Three : Fire completed"],
  ["Gardien de l'Équilibre",
   "Keeper of Balance"],
  ["L'ère de Korra terminée",
   "The Korra Era completed"],
  ["Avatar Accompli",
   "Fully Realized Avatar"],
  ["100% Avatar Legends complété",
   "Avatar Legends 100% completed"],
  ["Réinitialiser la progression Avatar Legends ?",
   "Reset your Avatar Legends progress?"],
  ["<p class=\"intro-lead\">Si vous êtes ici c'est que vous souhaitez lire et regarder l'univers Avatar Legends dans son ordre le plus optimisé, un mélange d'ordre chronologique et d'ordre de sortie, vous trouverez des détails supplémentaires en cliquant sur chaque média et tout ce site est garanti sans spoil majeur.</p><div class=\"intro-tags\"><span class=\"itag\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"/></svg>Ce guide est plutôt à destination des revisionnages, pour un premier visionnage regardez les séries et films mais si vous êtes persuadés d'aimer l'univers vous pouvez tout à fait suivre ce guide.</span></div><div class=\"keys-title\">Repères de lecture</div><div class=\"keys\"><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"3\" y=\"4\" width=\"18\" height=\"17\" rx=\"2\"/><path d=\"M8 2v4M16 2v4M3 10h18\"/></svg>Le calendrier</div><p>L'an 0 du calendrier est l'année du Génocide des Nomades de l'Air donc BG = Before Genocide / AG = After Genocide.</p></div><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M11 19 2 12l9-7v14zM22 19l-9-7 9-7v14z\"/></svg>Les flashback</div><p>Certains événements sont mieux à voir en tant que FLASHBACK pour comprendre et sont donc indiqués comme tel.</p></div><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 5a2 2 0 0 1 2-2h12v18H6a2 2 0 0 1-2-2z\"/><path d=\"M8 7h6M8 11h6\"/></svg>Les romans et comics</div><p>Les romans font majoritairement partie de la collection \"Les Chroniques de l'Avatar\" et racontent les histoires des Avatars du passé, ils sont loin d'être obligatoires mais ajoute du contexte, lisez des résumés si vous préférez.</p><p>Les comics font parti intégrante de l'oeuvre et continuent certaines intrigues des séries, certains sont très importants et d'autres anecdotiques, tout est indiqué.</p></div></div><details class=\"cuts\"><summary>Ce qui est écarté et pourquoi<span class=\"n\">5 entrées</span><svg class=\"chev\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m6 9 6 6 6-6\"/></svg></summary><div class=\"cuts-body\"><dl class=\"cuts-list\"><div class=\"cut\"><dt>Les Aventures Perdues</dt><dd>La plupart des histoires ne sont que des sketchs sans développement de personnage ni avancée de l'intrigue, les quelques exceptions sont dans la timeline.</dd></div><div class=\"cut\"><dt>Team Avatar Tales</dt><dd>La plupart des histoires ne sont que des sketchs sans développement de personnage ni avancée de l'intrigue, les quelques exceptions sont dans la timeline.</dd></div><div class=\"cut\"><dt>Les romans pour enfants</dt><dd>Seulement si vous êtes un enfant.</dd></div><div class=\"cut\"><dt>Les histoires du JDR papier</dt><dd>Les manuels du jeu de rôle papier sont une mine d'or en terme de lore mais impossible à caser dans une timeline chronologique.</dd></div><div class=\"cut\"><dt>Le jeu mobile Avatar Générations et les jeux sur Korra</dt><dd>Les serveurs sont hors ligne et/ou les jeux ne sont plus en vente.</dd></div></dl></div></details>",
   "<p class=\"intro-lead\">If you're here, it's because you want to read and watch the Avatar Legends universe in its most optimized order, a mix of chronological order and release order. You'll find extra details by clicking on each media, and this entire site is guaranteed free of major spoilers.</p><div class=\"intro-tags\"><span class=\"itag\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"/></svg>This guide is meant mostly for rewatches: for a first watch, go through the shows and movies, but if you're sure you'll love the universe, you can absolutely follow this guide.</span></div><div class=\"keys-title\">How to read this</div><div class=\"keys\"><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"3\" y=\"4\" width=\"18\" height=\"17\" rx=\"2\"/><path d=\"M8 2v4M16 2v4M3 10h18\"/></svg>The calendar</div><p>Year 0 of the calendar is the year of the Air Nomad Genocide, so BG = Before Genocide / AG = After Genocide.</p></div><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M11 19 2 12l9-7v14zM22 19l-9-7 9-7v14z\"/></svg>Flashbacks</div><p>Some events work better as a FLASHBACK for understanding, and are marked as such.</p></div><div class=\"key\"><div class=\"key-h\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 5a2 2 0 0 1 2-2h12v18H6a2 2 0 0 1-2-2z\"/><path d=\"M8 7h6M8 11h6\"/></svg>The novels and comics</div><p>Most of the novels belong to the \"Chronicles of the Avatar\" collection and tell the stories of the Avatars of the past. They are far from required, but they add context — read summaries instead if you prefer.</p><p>The comics are an integral part of the work and continue some of the storylines from the shows. Some are very important and others are minor, and it is all marked.</p></div></div><details class=\"cuts\"><summary>What's left out, and why<span class=\"n\">5 entries</span><svg class=\"chev\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m6 9 6 6 6-6\"/></svg></summary><div class=\"cuts-body\"><dl class=\"cuts-list\"><div class=\"cut\"><dt>The Lost Adventures</dt><dd>Most of the stories are just sketches with no character development and no plot progress; the few exceptions are in the timeline.</dd></div><div class=\"cut\"><dt>Team Avatar Tales</dt><dd>Most of the stories are just sketches with no character development and no plot progress; the few exceptions are in the timeline.</dd></div><div class=\"cut\"><dt>Kids' novels</dt><dd>Only if you are a child.</dd></div><div class=\"cut\"><dt>The tabletop RPG stories</dt><dd>The tabletop role-playing books are a goldmine of lore, but impossible to fit into a chronological timeline.</dd></div><div class=\"cut\"><dt>The mobile game Avatar Generations and the Korra games</dt><dd>The servers are offline and/or the games are no longer on sale.</dd></div></dl></div></details>"],
];
